<a href="https://colab.research.google.com/github/WHK-Scbert/TensorFlow/blob/main/LearnTensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

Initializing Tensor

In [ ]:
x = tf.constant(4.0, shape=(1,1), dtype=tf.float32)
x = tf.constant([[1,2,3],[1,2,3]])
x = tf.ones((3,3))
x = tf.zeros((2,3))
x = tf.eye(3) #eye for Indenticle matrix
x = tf.random.normal((3,3), mean=0, stddev=1)
x = tf.random.uniform((1,3), minval=0, maxval=1)
x = tf.range(start=1, limit=10, delta=2)
x = tf.cast(x, dtype=tf.float64)
print(x)

Mathematical Operation

In [ ]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])
z = tf.add(x, y)
z = x+y
print(z)
z = x/y
print(z)
z = tf.tensordot(x,y, axes=1) #Dot product
z = tf.reduce_sum(x*y, axis=0) #Dot product
print(z)
z = x ** 5
print(z)

#Matrix multiplication
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

z = tf.matmul(x,y)
print(z)
z = x @ y
print(z)

Indexing

In [ ]:
x = tf.constant([0,1,2,3,4,5,6])
'''
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])
'''
indices = tf.constant([0,3])
x_ind = tf.gather(x,indices)
#print(x_ind)
x = tf.constant([[1,2,3],
                 [3,4,5],
                 [5,6,7]])
print(x[0,:])
print(x[0:2,:])

Reshaping

In [60]:
x = tf.range(9)
print(x)

x = tf.reshape(x, (3,3))
print(x)
x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
